In [41]:
from tensorflow.keras.preprocessing.text import one_hot

In [42]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [43]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [44]:
## Define the vocabulary size
voc_size=10000

In [45]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [46]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8965, 1549, 7123, 2276],
 [8965, 1549, 7123, 776],
 [8965, 8232, 7123, 8010],
 [492, 335, 8300, 2886, 7078],
 [492, 335, 8300, 2886, 5572],
 [7220, 8965, 1858, 7123, 6359],
 [3287, 8173, 4906, 2886]]

In [47]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [48]:
import numpy as np

In [34]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8965 1549 7123 2276]
 [   0    0    0    0 8965 1549 7123  776]
 [   0    0    0    0 8965 8232 7123 8010]
 [   0    0    0  492  335 8300 2886 7078]
 [   0    0    0  492  335 8300 2886 5572]
 [   0    0    0 7220 8965 1858 7123 6359]
 [   0    0    0    0 3287 8173 4906 2886]]


In [49]:
## feature representation
dim=10

In [55]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None, dim))
model.compile('adam','mse')

d:\1_gen_ai_projects_kn\RNN_For_text_classification_sentiment_analysis\RNN_based_sentiment\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [56]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[[-0.01614793, -0.02760558,  0.03621143,  0.03420619,
         -0.00690527,  0.04389805,  0.03363451, -0.04493636,
          0.00150664, -0.0071773 ],
        [-0.01614793, -0.02760558,  0.03621143,  0.03420619,
         -0.00690527,  0.04389805,  0.03363451, -0.04493636,
          0.00150664, -0.0071773 ],
        [-0.01614793, -0.02760558,  0.03621143,  0.03420619,
         -0.00690527,  0.04389805,  0.03363451, -0.04493636,
          0.00150664, -0.0071773 ],
        [-0.01614793, -0.02760558,  0.03621143,  0.03420619,
         -0.00690527,  0.04389805,  0.03363451, -0.04493636,
          0.00150664, -0.0071773 ],
        [ 0.01921648,  0.02891219,  0.04927491, -0.01403165,
         -0.01855855, -0.0318829 ,  0.015003  , -0.04408623,
          0.00337808, -0.01416545],
        [-0.02814591,  0.01387187,  0.00165911, -0.01515613,
          0.02108126, -0.04390657,  0.04623802,  0.01912494,
         -0.02084175, -0.02225155],
        [-0.01636531, -0.0187122 ,  0.03415699, -0.0

In [52]:
embedded_docs[0]

array([   0,    0,    0,    0, 8965, 1549, 7123, 2276], dtype=int32)

In [53]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 655ms/step


array([[ 1.9368622e-02, -3.8922653e-03, -2.0752503e-02, -1.8897666e-02,
         2.1759700e-02,  4.4740736e-05,  1.4112208e-02,  3.1085718e-02,
        -4.5508277e-02,  1.3225440e-02],
       [ 1.9368622e-02, -3.8922653e-03, -2.0752503e-02, -1.8897666e-02,
         2.1759700e-02,  4.4740736e-05,  1.4112208e-02,  3.1085718e-02,
        -4.5508277e-02,  1.3225440e-02],
       [ 1.9368622e-02, -3.8922653e-03, -2.0752503e-02, -1.8897666e-02,
         2.1759700e-02,  4.4740736e-05,  1.4112208e-02,  3.1085718e-02,
        -4.5508277e-02,  1.3225440e-02],
       [ 1.9368622e-02, -3.8922653e-03, -2.0752503e-02, -1.8897666e-02,
         2.1759700e-02,  4.4740736e-05,  1.4112208e-02,  3.1085718e-02,
        -4.5508277e-02,  1.3225440e-02],
       [ 1.4387455e-02, -3.0262852e-02, -4.8861872e-02, -3.5622489e-02,
         4.4397209e-02, -3.7538633e-03,  4.5922700e-02,  1.4711287e-02,
         4.0421810e-02, -4.8228074e-02],
       [ 8.2784183e-03,  4.5002464e-02, -1.8973995e-02,  3.8500693e-02,
   